[project]
name = "EECS-449-group-16"
version = "0.2.0"
description = "Full-stack job discovery and application assistant built with Jac"
entry-point = "main"
kind = "web-app"
jac-version = "==0.37.11"

[dependencies]

[dependencies.npm]
jac-client-node = "1.0.7"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"

[dev-dependencies.pypi]
watchdog = ">=3.0.0"

[client]
